### PR TITLE
Updates heading order on Readme

### PR DESCRIPTION
**Pull request by jorydotcom**
Carol has requested that we move the Governance heading, which contains the PGB roster, up on the README for easier discovery.

### CODE REVIEW

**Comment by burnburn** [comment]
I'm fine with this change, or without it.  The more important change is adding the newer PGB members.

**Review by tasdienes — APPROVED** [review]

**Review by tkuhrt — APPROVED** [review]
LGTM -- will conflict with #15

**Comment by burnburn** [comment]
> LGTM -- will conflict with #15

Agreed.  This may require more than a rebase.  Once we get our 5 votes on #15 and merge, then @jorydotcom should replace this with a new PR.  It's just a move.  However, we don't have 5 votes on this one either.

**Review by tasdienes — APPROVED** [review]

**Review by chaals — APPROVED** [review]
LGTM

**Comment by burnburn** [comment]
This has been approved.  @jorydotcom please rebase or create a new PR that fixes the conflicts.  You can just merge when ready.

**Pull request merged**
